from setuptools import setup, find_packages

setup(
    name="aravqa",
    version="0.1.0",
    description="arabic-visual-question-answering",
    author="Mahmood Anaam",
    author_email="eng.mahmood.anaam@gmail.com",
    url="https://github.com/Mahmood-Anaam/arabic-visual-question-answering.git",
    license="MIT",
    packages=find_packages(where="aravqa"),
    package_dir={"": "aravqa"},
    install_requires=[
        "https://github.com/Mahmood-Anaam/vinvl/raw/main/vinvl-0.1.0-cp310-cp310-linux_x86_64.whl",
        "vinvl_bert@git+https://github.com/Mahmood-Anaam/vinvl_bert.git",
        "Violet@git+https://github.com/Mahmood-Anaam/Violet.git",
        "yacs",
        "torch",
        "torchvision",
        "transformers",
        "pytorch-transformers",
        "numpy",
        "opencv-python",
        "Pillow",
        "tqdm",
        "anytree",
        "pycocotools",
        "timm",
        "einops",
        "PyYAML",
        "cython",
        "ninja",
        "clint",
        "cityscapesScripts",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.9",
)
